spring.application.name=loan


spring.datasource.url=jdbc:postgresql://localhost:5432/loan_management
spring.datasource.username=palrpatel
spring.datasource.password=55555

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MySecretKeyForLoanManagementSystemApplication123456789
jwt.expiration=86400000